"""creating the initial tables

Revision ID: 9e39377f6b21
Revises: 
Create Date: 2026-08-15 16:15:35.066278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '9e39377f6b21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users_Table',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_Table_email'), 'Users_Table', ['email'], unique=True)
    op.create_index(op.f('ix_Users_Table_id'), 'Users_Table', ['id'], unique=False)
    op.create_index(op.f('ix_Users_Table_username'), 'Users_Table', ['username'], unique=True)
    op.create_table('Conversation_Table',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users_Table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Conversation_Table_id'), 'Conversation_Table', ['id'], unique=False)
    op.create_index(op.f('ix_Conversation_Table_title'), 'Conversation_Table', ['title'], unique=False)
    op.create_index(op.f('ix_Conversation_Table_user_id'), 'Conversation_Table', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users_Table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('processing_status', sa.Enum('UPLOADED', 'PROCESSING', 'CHUNKED', 'EMBEDDED', 'INDEXED', 'FAILED', name='document_status'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users_Table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('Document_chunks_table',
    sa.Column('Documnets_chunks_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['Documnets_chunks_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Document_chunks_table_Documnets_chunks_id'), 'Document_chunks_table', ['Documnets_chunks_id'], unique=False)
    op.create_index(op.f('ix_Document_chunks_table_chunk_index'), 'Document_chunks_table', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_Document_chunks_table_content'), 'Document_chunks_table', ['content'], unique=False)
    op.create_index(op.f('ix_Document_chunks_table_id'), 'Document_chunks_table', ['id'], unique=False)
    op.create_index(op.f('ix_Document_chunks_table_token_count'), 'Document_chunks_table', ['token_count'], unique=False)
    op.create_table('Message_Table',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content_messages', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation_Table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Message_Table_content_messages'), 'Message_Table', ['content_messages'], unique=False)
    op.create_index(op.f('ix_Message_Table_conversation_id'), 'Message_Table', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_Message_Table_id'), 'Message_Table', ['id'], unique=False)
    op.create_index(op.f('ix_Message_Table_role'), 'Message_Table', ['role'], unique=False)
    op.create_table('llm_request_logs',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation_Table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_request_logs_id'), 'llm_request_logs', ['id'], unique=False)
    op.create_table('sql_query_logs',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=False),
    sa.Column('execution_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversation_Table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_query_logs_id'), 'sql_query_logs', ['id'], unique=False)
    op.create_table('Embedding_Table',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding',Vector(1536),nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['Document_chunks_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Embedding_Table_chunk_id'), 'Embedding_Table', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_Embedding_Table_id'), 'Embedding_Table', ['id'], unique=False)
    op.create_table('Feedback_Table',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['Message_Table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Feedback_Table_id'), 'Feedback_Table', ['id'], unique=False)
    op.create_index(op.f('ix_Feedback_Table_message_id'), 'Feedback_Table', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Feedback_Table_message_id'), table_name='Feedback_Table')
    op.drop_index(op.f('ix_Feedback_Table_id'), table_name='Feedback_Table')
    op.drop_table('Feedback_Table')
    op.drop_index(op.f('ix_Embedding_Table_id'), table_name='Embedding_Table')
    op.drop_index(op.f('ix_Embedding_Table_chunk_id'), table_name='Embedding_Table')
    op.drop_table('Embedding_Table')
    op.drop_index(op.f('ix_sql_query_logs_id'), table_name='sql_query_logs')
    op.drop_table('sql_query_logs')
    op.drop_index(op.f('ix_llm_request_logs_id'), table_name='llm_request_logs')
    op.drop_table('llm_request_logs')
    op.drop_index(op.f('ix_Message_Table_role'), table_name='Message_Table')
    op.drop_index(op.f('ix_Message_Table_id'), table_name='Message_Table')
    op.drop_index(op.f('ix_Message_Table_conversation_id'), table_name='Message_Table')
    op.drop_index(op.f('ix_Message_Table_content_messages'), table_name='Message_Table')
    op.drop_table('Message_Table')
    op.drop_index(op.f('ix_Document_chunks_table_token_count'), table_name='Document_chunks_table')
    op.drop_index(op.f('ix_Document_chunks_table_id'), table_name='Document_chunks_table')
    op.drop_index(op.f('ix_Document_chunks_table_content'), table_name='Document_chunks_table')
    op.drop_index(op.f('ix_Document_chunks_table_chunk_index'), table_name='Document_chunks_table')
    op.drop_index(op.f('ix_Document_chunks_table_Documnets_chunks_id'), table_name='Document_chunks_table')
    op.drop_table('Document_chunks_table')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_Conversation_Table_user_id'), table_name='Conversation_Table')
    op.drop_index(op.f('ix_Conversation_Table_title'), table_name='Conversation_Table')
    op.drop_index(op.f('ix_Conversation_Table_id'), table_name='Conversation_Table')
    op.drop_table('Conversation_Table')
    op.drop_index(op.f('ix_Users_Table_username'), table_name='Users_Table')
    op.drop_index(op.f('ix_Users_Table_id'), table_name='Users_Table')
    op.drop_index(op.f('ix_Users_Table_email'), table_name='Users_Table')
    op.drop_table('Users_Table')
    # ### end Alembic commands ###
